# Generated by Django 3.2.4 on 2021-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('category', models.CharField(choices=[('appetizers', 'Appetizers'), ('snacks', 'Snacks'), ('Lunch', 'lunch'), ('Desserts', 'desserts'), ('drinks', 'Drinks')], default=None, max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
